# Generated by Django 5.0.7 on 2025-12-03 06:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rows', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('columns', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('benches_per_row', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')])),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['roll'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('benches_per_room', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seating.exam')),
                ('rooms', models.ManyToManyField(to='seating.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('column', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seating.allocation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seating.room')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seating.student')),
            ],
            options={
                'ordering': ['room', 'row', 'column', 'position'],
                'unique_together': {('allocation', 'room', 'row', 'column', 'position')},
            },
        ),
    ]
