# Generated by Django 5.0.7 on 2025-12-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')], default=1),
        ),
    ]
