# Generated by Django 5.0.7 on 2025-12-04 14:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0003_add_extra_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatassignment',
            options={'ordering': ['room', 'bench_no', 'seat_pos']},
        ),
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='room',
            name='benches_per_row',
        ),
        migrations.RemoveField(
            model_name='room',
            name='columns',
        ),
        migrations.AddField(
            model_name='allocation',
            name='base_pattern',
            field=models.JSONField(default=list, help_text='Base pattern for bench types'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='cols_per_room',
            field=models.IntegerField(default=5, help_text='Columns per room', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='allocation',
            name='distribution_strategy',
            field=models.CharField(choices=[('block', 'Block Distribution'), ('round_robin', 'Round Robin Distribution'), ('seeded_shuffle', 'Seeded Shuffle Distribution')], default='block', help_text='Student distribution strategy', max_length=20),
        ),
        migrations.AddField(
            model_name='allocation',
            name='flip_lr',
            field=models.BooleanField(default=False, help_text='Flip left-right seating'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='name',
            field=models.CharField(default='Default Allocation', help_text='Name for this allocation', max_length=200),
        ),
        migrations.AddField(
            model_name='allocation',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF file', null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='random_seed',
            field=models.IntegerField(blank=True, help_text='Random seed for reproducibility', null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='rows_per_room',
            field=models.IntegerField(default=6, help_text='Rows per room', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='allocation',
            name='seats_per_room',
            field=models.IntegerField(default=60, help_text='Seats per room', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='allocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Uploaded Excel file', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='room',
            name='benches',
            field=models.PositiveIntegerField(default=30, editable=False),
        ),
        migrations.AddField(
            model_name='room',
            name='benches_per_room',
            field=models.IntegerField(default=30, help_text='Total benches in room', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='room',
            name='cols',
            field=models.PositiveSmallIntegerField(default=5, help_text='Number of columns'),
        ),
        migrations.AddField(
            model_name='room',
            name='seats_per_room',
            field=models.IntegerField(default=60, help_text='Total seats in room', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='bench_no',
            field=models.IntegerField(default=1, help_text='Bench number in room', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='bench_type',
            field=models.CharField(choices=[('A', 'Type A (1st-2nd, 2nd-3rd, 3rd-1st)'), ('B', 'Type B (2nd-3rd, 3rd-1st, 1st-2nd)'), ('C', 'Type C (3rd-1st, 1st-2nd, 2nd-3rd)')], default='A', help_text='Type of bench arrangement', max_length=1),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='seat_pos',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', help_text='Left or right seat', max_length=5),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='benches_per_room',
            field=models.IntegerField(help_text='Benches per room', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='seating.exam'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='num_rooms',
            field=models.IntegerField(help_text='Number of rooms used', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='rooms',
            field=models.ManyToManyField(related_name='allocations', to='seating.room'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(help_text='Date of the exam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(help_text='Name of the exam', max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')], default=1, help_text='Target year for this exam'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Unique room identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rows',
            field=models.PositiveSmallIntegerField(default=6, help_text='Number of rows'),
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='seating.allocation'),
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='seating.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, help_text='Department (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Full name of the student', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(help_text='Unique roll number', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')], help_text='Academic year'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date'], name='seating_exa_date_7f36d0_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['year'], name='seating_exa_year_69a2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['allocation', 'room'], name='seating_sea_allocat_3cf359_idx'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['student'], name='seating_sea_student_7420c2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['year'], name='seating_stu_year_9221d4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll'], name='seating_stu_roll_8ad98c_idx'),
        ),
        migrations.RemoveField(
            model_name='seatassignment',
            name='column',
        ),
        migrations.RemoveField(
            model_name='seatassignment',
            name='position',
        ),
        migrations.RemoveField(
            model_name='seatassignment',
            name='row',
        ),
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together={('allocation', 'room', 'bench_no', 'seat_pos')},
        ),
    ]
