# Generated by Django 5.0.7 on 2025-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0005_add_row_column_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='report_file',
            field=models.FileField(blank=True, help_text='Allocation report JSON file', null=True, upload_to='reports/'),
        ),
    ]
