# Generated by Django 5.0.7 on 2025-12-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0006_allocation_report_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(help_text="Batch code (e.g., '231')", max_length=3, unique=True)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')], help_text='Mapped academic year')),
            ],
            options={
                'ordering': ['batch_code'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='batch_code',
            field=models.CharField(blank=True, help_text='Batch code extracted from roll', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dept_code',
            field=models.CharField(blank=True, help_text='Department code extracted from roll', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='serial',
            field=models.IntegerField(blank=True, help_text='Serial number extracted from roll', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')], help_text='Academic year (computed or admin-assigned)', null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['batch_code'], name='seating_stu_batch_c_f6b965_idx'),
        ),
    ]
