# Generated by Django 5.0.7 on 2025-12-14 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0007_batchmapping_student_batch_code_student_dept_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='benches_per_room',
            field=models.IntegerField(blank=True, help_text='Benches per room (null for dynamic rooms)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='cols_per_room',
            field=models.IntegerField(blank=True, help_text='Columns per room (null for dynamic rooms)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='rows_per_room',
            field=models.IntegerField(blank=True, help_text='Rows per room (null for dynamic rooms)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='seats_per_room',
            field=models.IntegerField(blank=True, help_text='Seats per room (null for dynamic rooms)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
