# Generated by Django 6.0 on 2025-12-14 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0008_make_cols_per_room_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='benches_per_room',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='cols_per_room',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='rows_per_room',
        ),
        migrations.AddField(
            model_name='allocation',
            name='semester_type',
            field=models.CharField(blank=True, choices=[('odd', 'Odd'), ('even', 'Even')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='seats_per_room',
            field=models.IntegerField(blank=True, help_text='Seats per room (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subject', max_length=200)),
                ('subject_code', models.CharField(blank=True, help_text='Optional subject code', max_length=20, null=True)),
                ('semester', models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester')], help_text='Semester number (1-6)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['semester', 'name'],
                'unique_together': {('name', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='allocations', to='seating.subject'),
        ),
    ]
