# Generated by Django 5.0.7 on 2025-12-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0009_remove_allocation_benches_per_room_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(blank=True, help_text='Department (optional)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Name of the subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester')], help_text='Semester number (1-6)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, help_text='Optional subject code', max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'semester', 'department')},
        ),
    ]
