# Generated by Django 5.0.7 on 2025-12-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0010_add_department_to_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='allocation_mode',
            field=models.CharField(choices=[('block_wise', 'Block-wise Allocation (No Random)'), ('cycle_wise', 'Cycle-wise Allocation (Random Inside Block)')], default='block_wise', help_text='Allocation mode: block-wise or cycle-wise', max_length=20),
        ),
    ]
