# Generated by Django 5.0.7 on 2026-01-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0011_add_allocation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='total_students',
            field=models.IntegerField(default=0, help_text='Total students allocated'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='year_1_students',
            field=models.IntegerField(default=0, help_text='Year 1 students'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='year_2_students',
            field=models.IntegerField(default=0, help_text='Year 2 students'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='year_3_students',
            field=models.IntegerField(default=0, help_text='Year 3 students'),
        ),
    ]
