# Generated by Django 5.0.7 on 2026-01-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0012_allocation_total_students_allocation_year_1_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocation_mode',
            field=models.CharField(choices=[('cycle', 'Cycle Mode (Ordered, Non-Random)'), ('block', 'Block Mode (Random Selection)')], default='cycle', help_text='Allocation mode: cycle or block', max_length=20),
        ),
    ]
