# Generated by Django 5.0.7 on 2026-01-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0013_alter_allocation_allocation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='academic_year',
            field=models.CharField(default='2024-2025', help_text='Academic year for PDF header', max_length=20),
        ),
        migrations.AddField(
            model_name='allocation',
            name='institution_name',
            field=models.CharField(default='Institution Name', help_text='Name of the institution for PDF header', max_length=255),
        ),
    ]
