# Generated by Django 5.0.7 on 2026-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0014_allocation_academic_year_allocation_institution_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'semester')},
        ),
        migrations.AddField(
            model_name='allocation',
            name='department',
            field=models.CharField(blank=True, help_text='Department name for PDF header', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='allocation_mode',
            field=models.CharField(choices=[('cycle', 'Cycle Mode (Ordered, Non-Random)'), ('block', 'Block Mode (Random Selection)'), ('hybrid', 'Hybrid Mode (Cycle + Smart Fill + Block)')], default='cycle', help_text='Allocation mode: cycle or block', max_length=20),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
    ]
