# Generated by Django 5.0.7 on 2026-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0015_alter_subject_unique_together_allocation_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='bench_type',
            field=models.CharField(choices=[('A', 'Bench Type A'), ('B', 'Bench Type B'), ('C', 'Bench Type C')], default='A', help_text='Type of bench arrangement', max_length=1),
        ),
    ]
