# Generated by Django 5.0.7 on 2026-01-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0016_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, help_text='🔴 Section (A/B/C etc. for section-locking)', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['section'], name='seating_stu_section_bb95b9_idx'),
        ),
    ]
