# Generated by Django 5.0.7 on 2026-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0017_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B')], default='A', help_text='Section (selected during upload)', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='upload_batch_id',
            field=models.CharField(blank=True, help_text='Upload batch identifier', max_length=50, null=True),
        ),
    ]
